# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: http://elasticsearch:9200 } #'%env(ELASTICSEARCH_URL)%'
    indexes:
        user:
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\User
                provider: ~
                finder: ~
            properties:
                username: ~
                firstName: ~
                lastName: ~
                email: ~
                password: ~